channels:
 - pytorch
 - defaults
dependencies: 
 - python=3.7.11
 - pip=21.2.2
 - pytorch=1.10
 - torchvision=0.11.2
 - torchaudio=0.10.1
 - cudatoolkit=10.2
 - matplotlib=3.4.3
 - numpy=1.21.2
 - pandas=1.3.5
 - scikit-learn=1.0.2
 - spacy=3.2.1
 - pip:
   - libvoikko==4.3
   - nlpaug==1.1.10
   - nltk==3.7
   - sentencepiece==0.1.96
   - spacy-fi-experimental-web-md==0.9.0
   - transformers==4.16.2
   - voikko==0.5
   - xgboost==1.6.2
